
development:
  adapter: postgresql
  encoding: unicode
  database: rubyfit
  pool: 5
  username: user
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: rubyfit_test
  pool: 5
  username: user
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: rubyfit
  pool: 5
  username: user
  password: password
